// Asignatura: 21GIIN Proyectos Programación
// Profesor: Eduardo Zamudio
// @author: Grupo 3
// Miembros:
//       @author:Fernando Hernandez Fernandez
//       @author:Javier Barbero Sales
//       @author:Martin Gonzalez Dominguez
// @version: 08/01/2023/package controlador;

package vista.usuario;

import controlador.Controlador;
import controlador.modelos.InmuebleControlador;
import controlador.modelos.UsuarioControlador;
import vista.inmueble.EdicionInmuebleFrame;


public class EdicionVecinoFrame extends javax.swing.JInternalFrame {
    private Controlador ctrl;
    private InmuebleControlador ic;
    private UsuarioControlador uc;
    
    /**
     * Creates new form edicionVecinoFrame
     */
    public EdicionVecinoFrame() {
        initComponents();
        ctrl = new Controlador();
        ic = new InmuebleControlador();
        uc = new UsuarioControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInmueblesEVF = new javax.swing.JTable();
        btnDetalleEU = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCancelarEU = new javax.swing.JButton();
        btnGuardarEU = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtTelefonoEU = new javax.swing.JTextField();
        txtApellidosEU = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtIdEU = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPasswordEU = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        txtUserNameEU = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtEmailEU = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNombreEU = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Inmuebles Asociados:");

        tblInmueblesEVF.setBackground(new java.awt.Color(242, 242, 242));
        tblInmueblesEVF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dirección", "Propietario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblInmueblesEVF);

        btnDetalleEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDetalleEU.setForeground(new java.awt.Color(51, 51, 51));
        btnDetalleEU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        btnDetalleEU.setText("Detalle");
        btnDetalleEU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnDetalleEU.setOpaque(true);
        btnDetalleEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetalleEUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDetalleEU, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalleEU)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnCancelarEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarEU.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarEU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar.png"))); // NOI18N
        btnCancelarEU.setText("Cancelar");
        btnCancelarEU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarEU.setOpaque(true);
        btnCancelarEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEUMouseClicked(evt);
            }
        });

        btnGuardarEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardarEU.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarEU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salvar.png"))); // NOI18N
        btnGuardarEU.setText("Guardar");
        btnGuardarEU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGuardarEU.setOpaque(true);
        btnGuardarEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarEUMouseClicked(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Telefono");

        txtTelefonoEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelefonoEU.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefonoEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoEUKeyTyped(evt);
            }
        });

        txtApellidosEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtApellidosEU.setForeground(new java.awt.Color(51, 51, 51));
        txtApellidosEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosEUKeyTyped(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Apellidos");

        jLabel29.setBackground(new java.awt.Color(51, 51, 51));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Id");

        txtIdEU.setEditable(false);
        txtIdEU.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdEU.setForeground(new java.awt.Color(51, 51, 51));
        txtIdEU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEUActionPerformed(evt);
            }
        });
        txtIdEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdEUKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Password");

        txtPasswordEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPasswordEU.setText("password");
        txtPasswordEU.setToolTipText("");
        txtPasswordEU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordEUFocusGained(evt);
            }
        });
        txtPasswordEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordEUKeyTyped(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("User name");

        txtUserNameEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUserNameEU.setForeground(new java.awt.Color(51, 51, 51));
        txtUserNameEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameEUKeyTyped(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Em@il");

        txtEmailEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmailEU.setForeground(new java.awt.Color(51, 51, 51));
        txtEmailEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailEUKeyTyped(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Nombre");

        txtNombreEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreEU.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEUKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailEU, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtUserNameEU, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPasswordEU)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtNombreEU, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtApellidosEU, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelefonoEU, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNombreEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtApellidosEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtTelefonoEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtEmailEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserNameEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23)
                    .addComponent(txtPasswordEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnDetalleEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalleEUMouseClicked
        if (tblInmueblesEVF.getSelectedRow() >= 0) {
            EdicionInmuebleFrame eif = new EdicionInmuebleFrame();
            ctrl.ocultarFrame(this);
            ctrl.mostrarFrame(eif);
            
            ic.cargarFormInmueble(
                eif.txtIdEI,
                eif.txtDireccionEI,
                eif.txtIdVecinoEI,
                eif.txtNombreEI,
                eif.txtApellidosEI,
                eif.txtTelefonoEI,
                eif.txtEmailEI,
                tblInmueblesEVF);
        }
    }//GEN-LAST:event_btnDetalleEUMouseClicked

    private void btnCancelarEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEUMouseClicked
        GestionUsuariosFrame guf = new GestionUsuariosFrame();
        ctrl.ocultarFrame(this);
        uc.cargarTablaUsuarios(guf.gUNombreText.getText(), guf.tblUsuarioGUF);
        ctrl.mostrarFrame(guf);
    }//GEN-LAST:event_btnCancelarEUMouseClicked

    private void btnGuardarEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEUMouseClicked
        GestionUsuariosFrame guf = new GestionUsuariosFrame();
        if (txtIdEU.getText().equals("")) {
            uc.registrarVecino(txtNombreEU, txtApellidosEU, txtTelefonoEU, txtEmailEU, txtUserNameEU, txtPasswordEU, guf.tblUsuarioGUF);
        } else {
            uc.updateUsuario(txtIdEU, txtNombreEU, txtApellidosEU, txtTelefonoEU, txtEmailEU, txtUserNameEU, txtPasswordEU, guf.tblUsuarioGUF);
        }
        ctrl.ocultarFrame(this);
        uc.cargarTablaUsuarios(guf.gUNombreText.getText(), guf.tblUsuarioGUF);
        ctrl.mostrarFrame(guf);
    }//GEN-LAST:event_btnGuardarEUMouseClicked

    private void txtTelefonoEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoEUKeyTyped
//        // TODO add your handling code here:
//        String texto = txtTelefonoEU.getText();
//        char caracter = evt.getKeyChar();
//        if (filtrarCaracteres(texto,caracter,"t")){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtTelefonoEUKeyTyped

    private void txtApellidosEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosEUKeyTyped
//        // TODO add your handling code here:
//        String texto = txtApellidosEU.getText();
//        char caracter = evt.getKeyChar();
//        if (filtrarCaracteres(texto,caracter,"l")){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtApellidosEUKeyTyped

    private void txtIdEUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEUActionPerformed

    }//GEN-LAST:event_txtIdEUActionPerformed

    private void txtIdEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEUKeyTyped
//        // TODO add your handling code here:
//        String texto = txtIdEU.getText();
//        char caracter = evt.getKeyChar();
//        if (filtrarCaracteres(texto,caracter,"l")){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtIdEUKeyTyped

    private void txtPasswordEUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordEUFocusGained
        txtPasswordEU.setText("");
    }//GEN-LAST:event_txtPasswordEUFocusGained

    private void txtPasswordEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordEUKeyTyped
//        // TODO add your handling code here:
//        String texto = txtNombreEU.getText();
//        char caracter = evt.getKeyChar();
//        if (filtrarCaracteres(texto,caracter,"m")){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtPasswordEUKeyTyped

    private void txtUserNameEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameEUKeyTyped
//        // TODO add your handling code here:
//        String texto = txtUserNameEU.getText();
//        char caracter = evt.getKeyChar();
//        if (filtrarCaracteres(texto,caracter,"ln")){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtUserNameEUKeyTyped

    private void txtEmailEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailEUKeyTyped
//        // TODO add your handling code here:
//        String texto = txtNombreEU.getText();
//        char caracter = evt.getKeyChar();
//        if (filtrarCaracteres(texto,caracter,"m")){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtEmailEUKeyTyped

    private void txtNombreEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEUKeyTyped
//        // TODO add your handling code here:
//        String texto = txtNombreEU.getText();
//        char caracter = evt.getKeyChar();
//        if (filtrarCaracteres(texto,caracter,"l")){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtNombreEUKeyTyped
    public void limpiarUserForm() {
            txtIdEU.setText("");
            txtNombreEU.setText("");
            txtApellidosEU.setText("");
            txtTelefonoEU.setText("");
            txtEmailEU.setText("");
            txtUserNameEU.setText("");
            txtPasswordEU.setText("");
        }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEU;
    private javax.swing.JButton btnDetalleEU;
    private javax.swing.JButton btnGuardarEU;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tblInmueblesEVF;
    public javax.swing.JTextField txtApellidosEU;
    public javax.swing.JTextField txtEmailEU;
    public javax.swing.JTextField txtIdEU;
    public javax.swing.JTextField txtNombreEU;
    public javax.swing.JPasswordField txtPasswordEU;
    public javax.swing.JTextField txtTelefonoEU;
    public javax.swing.JTextField txtUserNameEU;
    // End of variables declaration//GEN-END:variables
}
