// Asignatura: 21GIIN Proyectos Programación
// Profesor: Eduardo Zamudio
// @author: Grupo 3
// Miembros:
//       @author:Fernando Hernandez Fernandez
//       @author:Javier Barbero Sales
//       @author:Martin Gonzalez Dominguez
// @version: 08/01/2023/package controlador;

package vista.usuario;

import controlador.Controlador;
import controlador.modelos.InmuebleControlador;
import controlador.modelos.UsuarioControlador;

/**
 *  Clase GestionUsuariosFrame
 * 
 */
public class GestionUsuariosFrame extends javax.swing.JInternalFrame {
    //Controladores
    private Controlador ctrl;
    private UsuarioControlador uc;
    private InmuebleControlador ic;
    //Vistas
    private EdicionVecinoFrame evf;
    private RegistroAdminFrame raf;
    
    /**
     * Creates new form gestionUsuariosFrame
     */
    public GestionUsuariosFrame() {
        initComponents();
        ctrl  = new Controlador();
        uc = new UsuarioControlador();
        ic = new InmuebleControlador();
        evf = new EdicionVecinoFrame();
        raf = new RegistroAdminFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBorrarUsuarioGU = new javax.swing.JButton();
        btnAltaVecinoGU = new javax.swing.JButton();
        btnEditarUsuarioGU = new javax.swing.JButton();
        btnAltaAdminGU = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        gUNombreText = new javax.swing.JTextField();
        btnFiltrarUsuariosGU = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarioGUF = new javax.swing.JTable();
        btnCancelarGU = new javax.swing.JButton();

        setVisible(false);

        btnBorrarUsuarioGU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBorrarUsuarioGU.setForeground(new java.awt.Color(51, 51, 51));
        btnBorrarUsuarioGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/borrar.png"))); // NOI18N
        btnBorrarUsuarioGU.setText("Eliminar");
        btnBorrarUsuarioGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBorrarUsuarioGU.setOpaque(true);
        btnBorrarUsuarioGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarUsuarioGUMouseClicked(evt);
            }
        });

        btnAltaVecinoGU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAltaVecinoGU.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaVecinoGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alta_vecino.png"))); // NOI18N
        btnAltaVecinoGU.setText("Alta Vecino");
        btnAltaVecinoGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaVecinoGU.setOpaque(true);
        btnAltaVecinoGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaVecinoGUMouseClicked(evt);
            }
        });

        btnEditarUsuarioGU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditarUsuarioGU.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarUsuarioGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/editar.png"))); // NOI18N
        btnEditarUsuarioGU.setText("Editar / Detalle");
        btnEditarUsuarioGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnEditarUsuarioGU.setOpaque(true);
        btnEditarUsuarioGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioGUMouseClicked(evt);
            }
        });

        btnAltaAdminGU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAltaAdminGU.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaAdminGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gerente.png"))); // NOI18N
        btnAltaAdminGU.setText("Alta Administrador");
        btnAltaAdminGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaAdminGU.setOpaque(true);
        btnAltaAdminGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaAdminGUMouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nombre");

        gUNombreText.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        gUNombreText.setForeground(new java.awt.Color(51, 51, 51));

        btnFiltrarUsuariosGU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFiltrarUsuariosGU.setForeground(new java.awt.Color(51, 51, 51));
        btnFiltrarUsuariosGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar.png"))); // NOI18N
        btnFiltrarUsuariosGU.setText("Consultar");
        btnFiltrarUsuariosGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnFiltrarUsuariosGU.setOpaque(true);
        btnFiltrarUsuariosGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarUsuariosGUMouseClicked(evt);
            }
        });

        tblUsuarioGUF.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        tblUsuarioGUF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Apellidos", "Telefono", "Email", "userName", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarioGUF.setRowHeight(25);
        jScrollPane1.setViewportView(tblUsuarioGUF);

        btnCancelarGU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarGU.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar.png"))); // NOI18N
        btnCancelarGU.setText("Cancelar");
        btnCancelarGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarGU.setOpaque(true);
        btnCancelarGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarGUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAltaVecinoGU, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAltaAdminGU, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarUsuarioGU, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarUsuarioGU, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarGU, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gUNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrarUsuariosGU, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBorrarUsuarioGU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarUsuarioGU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAltaAdminGU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAltaVecinoGU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gUNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarUsuariosGU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton para eliminar un usuario 
     * @param evt evento recibido
     */
    private void btnBorrarUsuarioGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioGUMouseClicked
        uc.eliminarUsuario(tblUsuarioGUF);
    }//GEN-LAST:event_btnBorrarUsuarioGUMouseClicked
    
    /**
     * Evento pulsar el boton Alta vecino
     * @param evt evento recibido
     */
    private void btnAltaVecinoGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaVecinoGUMouseClicked
        if (evf.isVisible() == false) {
            ctrl.ocultarFrame(this, ctrl.mfamvc.panelDatos);
            ctrl.mostrarFrame(evf, ctrl.mfamvc.panelDatos);      
        }
        evf.limpiarUserForm();
    }//GEN-LAST:event_btnAltaVecinoGUMouseClicked
    
    /**
     * Evento pulsar el boton editar usuario
     * @param evt evento recibido
     */
    private void btnEditarUsuarioGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioGUMouseClicked
        if (tblUsuarioGUF.getSelectedRow() >= 0) {
            if (evf.isVisible() == false) {
                ctrl.ocultarFrame(this, ctrl.mfamvc.panelDatos);
                ctrl.mostrarFrame(evf, ctrl.mfamvc.panelDatos); 
            }
            uc.cargarFormUsuario(tblUsuarioGUF, evf.txtIdEU, evf.txtNombreEU, evf.txtApellidosEU, evf.txtTelefonoEU, evf.txtEmailEU, evf.txtUserNameEU, evf.txtPasswordEU);
            ic.cargarTablaInmueblesVecino(Integer.parseInt(evf.txtIdEU.getText()), evf.tblInmueblesEVF);
        }
    }//GEN-LAST:event_btnEditarUsuarioGUMouseClicked

    /**
     * Evento pulsar el boton Alta administrador
     * @param evt evento recibido
     */
    private void btnAltaAdminGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaAdminGUMouseClicked
        if (raf.isVisible() == false) {
            ctrl.ocultarFrame(this, ctrl.mfamvc.panelDatos);
            ctrl.mostrarFrame(raf, ctrl.mfamvc.panelDatos);
        }
    }//GEN-LAST:event_btnAltaAdminGUMouseClicked

    /**
     * Evento pulsar el boton filtrar usuarios
     * @param evt evento recibido
     */
    private void btnFiltrarUsuariosGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarUsuariosGUMouseClicked
        uc.cargarTablaUsuarios(gUNombreText.getText(), tblUsuarioGUF);
    }//GEN-LAST:event_btnFiltrarUsuariosGUMouseClicked

    /**
     * Evento pulsar el boton Cancelar, cierra el internal frame
     * @param evt evento recibido
     */
    private void btnCancelarGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarGUMouseClicked
        ctrl.ocultarFrame(this,ctrl.mfamvc.panelDatos);
    }//GEN-LAST:event_btnCancelarGUMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaAdminGU;
    private javax.swing.JButton btnAltaVecinoGU;
    private javax.swing.JButton btnBorrarUsuarioGU;
    private javax.swing.JButton btnCancelarGU;
    private javax.swing.JButton btnEditarUsuarioGU;
    private javax.swing.JButton btnFiltrarUsuariosGU;
    public javax.swing.JTextField gUNombreText;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblUsuarioGUF;
    // End of variables declaration//GEN-END:variables
}
