/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.modelos.UsuarioControlador;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fer
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        panel_fondo = new javax.swing.JPanel();
        campo_usuario = new javax.swing.JTextField();
        etiqueta_usuario = new javax.swing.JLabel();
        etiqueta_pass = new javax.swing.JLabel();
        etiqueta_login = new javax.swing.JLabel();
        boton_aceptar = new javax.swing.JButton();
        campo_password = new javax.swing.JPasswordField();
        etiqueta_nombrePrograma = new javax.swing.JLabel();
        etiqueta_imagen = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        etiqueta_version = new javax.swing.JLabel();
        etiqueta_autores = new javax.swing.JLabel();
        etiqueta_nombreProyecto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Log in VIU Comunidad"); // NOI18N
        setResizable(false);

        panel_fondo.setBackground(new java.awt.Color(255, 255, 255));
        panel_fondo.setName("Log in VIU Comunidad"); // NOI18N

        campo_usuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_usuario.setForeground(new java.awt.Color(51, 51, 51));

        etiqueta_usuario.setBackground(new java.awt.Color(51, 51, 51));
        etiqueta_usuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta_usuario.setText("Usuario");

        etiqueta_pass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        etiqueta_pass.setText("Password");

        etiqueta_login.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        etiqueta_login.setForeground(new java.awt.Color(51, 51, 51));
        etiqueta_login.setText("Inicio Sesión");

        boton_aceptar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_aceptar.setForeground(new java.awt.Color(51, 51, 51));
        boton_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/enter.png"))); // NOI18N
        boton_aceptar.setText("Aceptar");
        boton_aceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        boton_aceptar.setOpaque(true);
        boton_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_aceptarMouseClicked(evt);
            }
        });
        boton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aceptarActionPerformed(evt);
            }
        });

        campo_password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campo_password.setText("password");
        campo_password.setToolTipText("");
        campo_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_passwordFocusGained(evt);
            }
        });
        campo_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_passwordActionPerformed(evt);
            }
        });
        campo_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_passwordKeyTyped(evt);
            }
        });

        etiqueta_nombrePrograma.setFont(new java.awt.Font("SF Pro Display", 0, 24)); // NOI18N
        etiqueta_nombrePrograma.setForeground(new java.awt.Color(51, 51, 51));
        etiqueta_nombrePrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_nombrePrograma.setText("VIU Comunidad");

        etiqueta_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addComponent(etiqueta_login)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addComponent(etiqueta_imagen)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addComponent(etiqueta_nombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_password, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqueta_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqueta_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addComponent(boton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(etiqueta_imagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(etiqueta_nombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqueta_login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqueta_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiqueta_pass)
                .addGap(8, 8, 8)
                .addComponent(campo_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(boton_aceptar)
                .addGap(28, 28, 28))
        );

        campo_usuario.getAccessibleContext().setAccessibleName("userName");
        campo_usuario.getAccessibleContext().setAccessibleDescription("");
        campo_password.getAccessibleContext().setAccessibleName("pwd");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        panelFooter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        etiqueta_version.setForeground(new java.awt.Color(153, 153, 153));
        etiqueta_version.setText("versión: 2022 - 2023");

        etiqueta_autores.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        etiqueta_autores.setForeground(new java.awt.Color(153, 153, 153));
        etiqueta_autores.setText("Grupo3: Fernando Hernandez Fernandez / Javier Barbero Sales / Martin Gonzalez Dominguez ");

        etiqueta_nombreProyecto.setForeground(new java.awt.Color(153, 153, 153));
        etiqueta_nombreProyecto.setText("@ViuComunidad_Grupo3");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFooterLayout.createSequentialGroup()
                        .addComponent(etiqueta_autores)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelFooterLayout.createSequentialGroup()
                        .addComponent(etiqueta_nombreProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiqueta_version)
                        .addGap(25, 25, 25))))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_nombreProyecto)
                    .addComponent(etiqueta_version))
                .addGap(18, 18, 18)
                .addComponent(etiqueta_autores)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Log in VIU Comunidad");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_passwordFocusGained
        campo_password.setText("");
    }//GEN-LAST:event_campo_passwordFocusGained

    private void boton_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_aceptarMouseClicked
        UsuarioControlador uc = new UsuarioControlador();
        String userName = campo_usuario.getText();
        String pwd = campo_password.getText();
        uc.autenticarUsuario(userName, pwd);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_boton_aceptarMouseClicked

    private void campo_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_passwordActionPerformed

    private void boton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_aceptarActionPerformed

    private void campo_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_passwordKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER){
            UsuarioControlador uc = new UsuarioControlador();
            String userName = campo_usuario.getText();
            String pwd = campo_password.getText();
            uc.autenticarUsuario(userName, pwd);
        }
    }//GEN-LAST:event_campo_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aceptar;
    private javax.swing.JPasswordField campo_password;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JLabel etiqueta_autores;
    private javax.swing.JLabel etiqueta_imagen;
    private javax.swing.JLabel etiqueta_login;
    private javax.swing.JLabel etiqueta_nombrePrograma;
    private javax.swing.JLabel etiqueta_nombreProyecto;
    private javax.swing.JLabel etiqueta_pass;
    private javax.swing.JLabel etiqueta_usuario;
    private javax.swing.JLabel etiqueta_version;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panel_fondo;
    // End of variables declaration//GEN-END:variables
}
