/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import controlador.usuario.UsuarioControlador;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author fer
 */
public class MainFrameVecino extends javax.swing.JFrame {

    Controlador ctrl = new Controlador();
    UsuarioControlador uc = new UsuarioControlador();

    /**
     * Creates new form MainFrame
     */
    public MainFrameVecino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JDesktopPane();
        panelDatos = new javax.swing.JDesktopPane();
        gestionUsuariosFrame = new javax.swing.JInternalFrame();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        gUNombreText = new javax.swing.JTextField();
        btnFiltrarUsuariosGU = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAltaVecinoGU = new javax.swing.JButton();
        btnAltaAdminGU = new javax.swing.JButton();
        btnEditarUsuarioGU = new javax.swing.JButton();
        btnBorrarUsuarioGU = new javax.swing.JButton();
        registroAdminFrame = new javax.swing.JInternalFrame();
        jLabel14 = new javax.swing.JLabel();
        txtNombreRA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPasswordRA = new javax.swing.JPasswordField();
        btnAltaAdmin = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtApellidosRA = new javax.swing.JTextField();
        txtUserNameRA = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTelefonoRA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtEmailRA = new javax.swing.JTextField();
        btnCancelarAltaAdmin = new javax.swing.JButton();
        edicionVecinoFrame = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtIdEU = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNombreEU = new javax.swing.JTextField();
        txtApellidosEU = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTelefonoEU = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtEmailEU = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtUserNameEU = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPasswordEU = new javax.swing.JPasswordField();
        btnGuardarEU = new javax.swing.JButton();
        btnCancelarEU = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnCancelarEU1 = new javax.swing.JButton();
        panelFooter = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VIU Comunidad");
        setResizable(false);

        panelCabecera.setBackground(new java.awt.Color(255, 255, 255));

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelDatos.setPreferredSize(new java.awt.Dimension(1000, 600));

        gestionUsuariosFrame.setBackground(new java.awt.Color(255, 255, 255));
        gestionUsuariosFrame.setBorder(null);
        gestionUsuariosFrame.setForeground(new java.awt.Color(255, 255, 255));
        gestionUsuariosFrame.setTitle("Gestion Usuarios");
        gestionUsuariosFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        gestionUsuariosFrame.setVisible(false);

        jDesktopPane3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nombre");

        gUNombreText.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        gUNombreText.setForeground(new java.awt.Color(51, 51, 51));

        btnFiltrarUsuariosGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnFiltrarUsuariosGU.setForeground(new java.awt.Color(51, 51, 51));
        btnFiltrarUsuariosGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar.png"))); // NOI18N
        btnFiltrarUsuariosGU.setText("Consultar");
        btnFiltrarUsuariosGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnFiltrarUsuariosGU.setOpaque(true);
        btnFiltrarUsuariosGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarUsuariosGUMouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Apellidos", "Telefono", "Email", "userName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane3.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(gUNombreText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnFiltrarUsuariosGU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gUNombreText)
                        .addGap(12, 12, 12)
                        .addComponent(btnFiltrarUsuariosGU, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrarUsuariosGU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gUNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAltaVecinoGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnAltaVecinoGU.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaVecinoGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alta_vecino.png"))); // NOI18N
        btnAltaVecinoGU.setText("Alta Vecino");
        btnAltaVecinoGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaVecinoGU.setOpaque(true);
        btnAltaVecinoGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaVecinoGUMouseClicked(evt);
            }
        });

        btnAltaAdminGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnAltaAdminGU.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaAdminGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gerente.png"))); // NOI18N
        btnAltaAdminGU.setText("Alta Administrador");
        btnAltaAdminGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaAdminGU.setOpaque(true);
        btnAltaAdminGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaAdminGUMouseClicked(evt);
            }
        });

        btnEditarUsuarioGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnEditarUsuarioGU.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarUsuarioGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/editar.png"))); // NOI18N
        btnEditarUsuarioGU.setText("Editar");
        btnEditarUsuarioGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnEditarUsuarioGU.setOpaque(true);
        btnEditarUsuarioGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioGUMouseClicked(evt);
            }
        });
        btnEditarUsuarioGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioGUActionPerformed(evt);
            }
        });

        btnBorrarUsuarioGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnBorrarUsuarioGU.setForeground(new java.awt.Color(51, 51, 51));
        btnBorrarUsuarioGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/borrar.png"))); // NOI18N
        btnBorrarUsuarioGU.setText("Eliminar");
        btnBorrarUsuarioGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBorrarUsuarioGU.setOpaque(true);
        btnBorrarUsuarioGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarUsuarioGUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gestionUsuariosFrameLayout = new javax.swing.GroupLayout(gestionUsuariosFrame.getContentPane());
        gestionUsuariosFrame.getContentPane().setLayout(gestionUsuariosFrameLayout);
        gestionUsuariosFrameLayout.setHorizontalGroup(
            gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionUsuariosFrameLayout.createSequentialGroup()
                .addComponent(jDesktopPane3)
                .addContainerGap())
            .addGroup(gestionUsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAltaVecinoGU, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAltaAdminGU, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarUsuarioGU, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrarUsuarioGU, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gestionUsuariosFrameLayout.setVerticalGroup(
            gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestionUsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAltaAdminGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarUsuarioGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarUsuarioGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAltaVecinoGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        registroAdminFrame.setBackground(new java.awt.Color(255, 255, 255));
        registroAdminFrame.setForeground(new java.awt.Color(255, 255, 255));
        registroAdminFrame.setTitle("Registro Administrador");
        registroAdminFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        registroAdminFrame.setVisible(false);

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nombre");

        txtNombreRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtNombreRA.setForeground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Password");

        txtPasswordRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtPasswordRA.setText("password");
        txtPasswordRA.setToolTipText("");
        txtPasswordRA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordRAFocusGained(evt);
            }
        });

        btnAltaAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAltaAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaAdmin.setText("Aceptar");
        btnAltaAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaAdmin.setOpaque(true);
        btnAltaAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaAdminMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Apellidos");

        txtApellidosRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtApellidosRA.setForeground(new java.awt.Color(51, 51, 51));

        txtUserNameRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtUserNameRA.setForeground(new java.awt.Color(51, 51, 51));

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("User name");

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Telefono");

        txtTelefonoRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtTelefonoRA.setForeground(new java.awt.Color(51, 51, 51));

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Em@il");

        txtEmailRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtEmailRA.setForeground(new java.awt.Color(51, 51, 51));

        btnCancelarAltaAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarAltaAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarAltaAdmin.setText("Cancelar");
        btnCancelarAltaAdmin.setToolTipText("");
        btnCancelarAltaAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarAltaAdmin.setOpaque(true);
        btnCancelarAltaAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarAltaAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout registroAdminFrameLayout = new javax.swing.GroupLayout(registroAdminFrame.getContentPane());
        registroAdminFrame.getContentPane().setLayout(registroAdminFrameLayout);
        registroAdminFrameLayout.setHorizontalGroup(
            registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroAdminFrameLayout.createSequentialGroup()
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroAdminFrameLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroAdminFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailRA, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registroAdminFrameLayout.createSequentialGroup()
                        .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registroAdminFrameLayout.createSequentialGroup()
                                .addComponent(txtUserNameRA, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPasswordRA))
                            .addGroup(registroAdminFrameLayout.createSequentialGroup()
                                .addComponent(txtNombreRA, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidosRA, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefonoRA, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroAdminFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        registroAdminFrameLayout.setVerticalGroup(
            registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroAdminFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNombreRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtApellidosRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtTelefonoRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtEmailRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtUserNameRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtPasswordRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        edicionVecinoFrame.setBackground(new java.awt.Color(255, 255, 255));
        edicionVecinoFrame.setForeground(new java.awt.Color(255, 255, 255));
        edicionVecinoFrame.setTitle("Editar / Detalle Vecino");
        edicionVecinoFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        edicionVecinoFrame.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel29.setBackground(new java.awt.Color(51, 51, 51));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Id");

        txtIdEU.setEditable(false);
        txtIdEU.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtIdEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Nombre");

        txtNombreEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtNombreEU.setForeground(new java.awt.Color(51, 51, 51));

        txtApellidosEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtApellidosEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Apellidos");

        txtTelefonoEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtTelefonoEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Telefono");

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Em@il");

        txtEmailEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtEmailEU.setForeground(new java.awt.Color(51, 51, 51));
        txtEmailEU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEUActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("User name");

        txtUserNameEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtUserNameEU.setForeground(new java.awt.Color(51, 51, 51));
        txtUserNameEU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameEUActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Password");

        txtPasswordEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtPasswordEU.setText("password");
        txtPasswordEU.setToolTipText("");
        txtPasswordEU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordEUFocusGained(evt);
            }
        });

        btnGuardarEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardarEU.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarEU.setText("Guardar");
        btnGuardarEU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGuardarEU.setOpaque(true);
        btnGuardarEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarEUMouseClicked(evt);
            }
        });
        btnGuardarEU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEUActionPerformed(evt);
            }
        });

        btnCancelarEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarEU.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarEU.setText("Cancelar");
        btnCancelarEU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarEU.setOpaque(true);
        btnCancelarEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUserNameEU, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtPasswordEU))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailEU, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addComponent(btnGuardarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreEU, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidosEU, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefonoEU, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtIdEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(txtTelefonoEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserNameEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23)
                    .addComponent(txtPasswordEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTable3.setBackground(new java.awt.Color(242, 242, 242));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Inmuebles Asociados:");

        btnCancelarEU1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarEU1.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarEU1.setText("Detalle");
        btnCancelarEU1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarEU1.setOpaque(true);
        btnCancelarEU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEU1MouseClicked(evt);
            }
        });
        btnCancelarEU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEU1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarEU1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarEU1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout edicionVecinoFrameLayout = new javax.swing.GroupLayout(edicionVecinoFrame.getContentPane());
        edicionVecinoFrame.getContentPane().setLayout(edicionVecinoFrameLayout);
        edicionVecinoFrameLayout.setHorizontalGroup(
            edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        edicionVecinoFrameLayout.setVerticalGroup(
            edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        panelDatos.setLayer(gestionUsuariosFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDatos.setLayer(registroAdminFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDatos.setLayer(edicionVecinoFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gestionUsuariosFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1008, Short.MAX_VALUE)))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(registroAdminFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1008, Short.MAX_VALUE)))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(edicionVecinoFrame, 0, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1008, Short.MAX_VALUE)))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gestionUsuariosFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(663, Short.MAX_VALUE)))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(registroAdminFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(663, Short.MAX_VALUE)))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(edicionVecinoFrame, 0, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(663, Short.MAX_VALUE)))
        );

        panelCabecera.setLayer(panelDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelFooter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Tipo:");

        jLabel36.setForeground(new java.awt.Color(153, 153, 153));
        jLabel36.setText("Usuario:");

        jLabel37.setForeground(new java.awt.Color(153, 153, 153));
        jLabel37.setText("XXXXXXXXX");

        jLabel38.setForeground(new java.awt.Color(153, 153, 153));
        jLabel38.setText("Vecino");

        panelFooter.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelFooter.setLayer(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelFooter.setLayer(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelFooter.setLayer(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addGap(74, 74, 74)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addContainerGap(720, Short.MAX_VALUE))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icono2.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("72 Light", 1, 12)); // NOI18N
        jLabel34.setText("VIU Comunidad (Grupo3)");

        jLabel35.setFont(new java.awt.Font("72 Light", 0, 12)); // NOI18N
        jLabel35.setText("Gestión y Administración de Comunidades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCabecera)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)))
                    .addComponent(panelFooter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCabecera)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFooter)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordRAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordRAFocusGained
        txtPasswordRV.setText("");
    }//GEN-LAST:event_txtPasswordRAFocusGained

    private void btnAltaAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaAdminMouseClicked
        ctrl.registrarAdmin();
        ctrl.cargarTablaUsuarios(gUNombreText.getText());
        registroAdminFrame.hide();
    }//GEN-LAST:event_btnAltaAdminMouseClicked

    private void txtPasswordEUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordEUFocusGained

    }//GEN-LAST:event_txtPasswordEUFocusGained

    private void btnGuardarEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEUMouseClicked
        ctrl.updateUsuario();
        edicionVecinoFrame.hide();;
    }//GEN-LAST:event_btnGuardarEUMouseClicked

    private void btnCancelarEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEUMouseClicked
        edicionVecinoFrame.hide();
    }//GEN-LAST:event_btnCancelarEUMouseClicked

    private void btnCancelarAltaAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarAltaAdminMouseClicked
        registroAdminFrame.hide();
    }//GEN-LAST:event_btnCancelarAltaAdminMouseClicked

    private void btnBorrarUsuarioGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioGUMouseClicked
        ctrl.eliminarUsuario();
    }//GEN-LAST:event_btnBorrarUsuarioGUMouseClicked

    private void btnEditarUsuarioGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioGUMouseClicked
        if (jTable1.getSelectedRow() > 0) {
            if (edicionVecinoFrame.isVisible() == false) {
                dimensionarFrameDatos(edicionVecinoFrame);
            }
            ctrl.cargarFormUsuario();
            edicionVecinoFrame.show();
        }
    }//GEN-LAST:event_btnEditarUsuarioGUMouseClicked

    private void btnFiltrarUsuariosGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarUsuariosGUMouseClicked
        ctrl.cargarTablaUsuarios(gUNombreText.getText());
    }//GEN-LAST:event_btnFiltrarUsuariosGUMouseClicked

    private void btnAltaAdminGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaAdminGUMouseClicked
        if (registroAdminFrame.isVisible() == false) {
            dimensionarFrameDatos(registroAdminFrame);
        }
        registroAdminFrame.show();
    }//GEN-LAST:event_btnAltaAdminGUMouseClicked

    private void btnAltaVecinoGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaVecinoGUMouseClicked
        if (registroVecinoFrame.isVisible() == false) {
            dimensionarFrameDatos(registroVecinoFrame);
        }
        registroVecinoFrame.show();
    }//GEN-LAST:event_btnAltaVecinoGUMouseClicked

    private void btnEditarUsuarioGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioGUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarUsuarioGUActionPerformed

    private void txtEmailEUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEUActionPerformed

    private void txtUserNameEUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameEUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameEUActionPerformed

    private void btnCancelarEU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEU1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEU1MouseClicked

    private void btnCancelarEU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEU1ActionPerformed

    private void btnGuardarEUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameVecino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameVecino().setVisible(true);
            }
        });
    }

    private void dimensionarFrameDatos(JInternalFrame jIF) {
        jIF.setLocation((btnUsuarios.location().x),
                (btnUsuarios.location().y + btnUsuarios.getSize().height + 5));
        jIF.setSize(JFrame.WIDTH - 30, JFrame.HEIGHT - jLabel4.getSize().height - 30 - btnUsuarios.getSize().height);
        jIF.setVisible(true);
        jIF.show();

    }

    public void inicioMain() {
        registroVecinoFrame.hide();
        gestionUsuariosFrame.hide();
        registroAdminFrame.hide();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaAdmin;
    private javax.swing.JButton btnAltaAdminGU;
    private javax.swing.JButton btnAltaVecinoGU;
    private javax.swing.JButton btnBorrarUsuarioGU;
    private javax.swing.JButton btnCancelarAltaAdmin;
    private javax.swing.JButton btnCancelarEU;
    private javax.swing.JButton btnCancelarEU1;
    private javax.swing.JButton btnEditarUsuarioGU;
    private javax.swing.JButton btnFiltrarUsuariosGU;
    private javax.swing.JButton btnGuardarEU;
    public javax.swing.JInternalFrame edicionVecinoFrame;
    public javax.swing.JTextField gUNombreText;
    private javax.swing.JInternalFrame gestionUsuariosFrame;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JDesktopPane panelCabecera;
    private javax.swing.JDesktopPane panelDatos;
    private javax.swing.JDesktopPane panelFooter;
    public javax.swing.JInternalFrame registroAdminFrame;
    public javax.swing.JTextField txtApellidosEU;
    public javax.swing.JTextField txtApellidosRA;
    public javax.swing.JTextField txtEmailEU;
    public javax.swing.JTextField txtEmailRA;
    public javax.swing.JTextField txtIdEU;
    public javax.swing.JTextField txtNombreEU;
    public javax.swing.JTextField txtNombreRA;
    public javax.swing.JPasswordField txtPasswordEU;
    public javax.swing.JPasswordField txtPasswordRA;
    public javax.swing.JTextField txtTelefonoEU;
    public javax.swing.JTextField txtTelefonoRA;
    public javax.swing.JTextField txtUserNameEU;
    public javax.swing.JTextField txtUserNameRA;
    // End of variables declaration//GEN-END:variables
}
