/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import controlador.modelos.InmuebleControlador;
import controlador.modelos.UsuarioControlador;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author fer
 */
public class MainFrameAdmin extends javax.swing.JFrame {

    Controlador ctrl = new Controlador();
    UsuarioControlador uc = new UsuarioControlador();
    InmuebleControlador ic = new InmuebleControlador();

    /**
     * Creates new form MainFrame
     */
    public MainFrameAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JDesktopPane();
        btnLiquidaciones = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnInmuebles = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        panelFooter = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        panelDatos = new javax.swing.JDesktopPane();
        gestionUsuariosFrame = new javax.swing.JInternalFrame();
        btnAltaVecinoGU = new javax.swing.JButton();
        btnAltaAdminGU = new javax.swing.JButton();
        btnEditarUsuarioGU = new javax.swing.JButton();
        btnBorrarUsuarioGU = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        gUNombreText = new javax.swing.JTextField();
        btnFiltrarUsuariosGU = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBorrarUsuarioGU3 = new javax.swing.JButton();
        registroAdminFrame = new javax.swing.JInternalFrame();
        jLabel14 = new javax.swing.JLabel();
        txtNombreRA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPasswordRA = new javax.swing.JPasswordField();
        btnAltaAdmin = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtApellidosRA = new javax.swing.JTextField();
        txtUserNameRA = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTelefonoRA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtEmailRA = new javax.swing.JTextField();
        btnCancelarAltaAdmin = new javax.swing.JButton();
        edicionVecinoFrame = new javax.swing.JInternalFrame();
        jLabel29 = new javax.swing.JLabel();
        txtIdEU = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNombreEU = new javax.swing.JTextField();
        txtApellidosEU = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTelefonoEU = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtEmailEU = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtUserNameEU = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPasswordEU = new javax.swing.JPasswordField();
        btnGuardarEU = new javax.swing.JButton();
        btnCancelarEU = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnCancelarEU1 = new javax.swing.JButton();
        gestionInmueblesFrame = new javax.swing.JInternalFrame();
        btnAltaInmuebleGI = new javax.swing.JButton();
        javax.swing.JButton btnEditarInmuebleGI = new javax.swing.JButton();
        btnBorrarInmuebleGI = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        gIDireccionText = new javax.swing.JTextField();
        btnFiltrarInmueblesGI = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnCancelarGI = new javax.swing.JButton();
        edicionInmuebleFrame = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtIdEI = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtDireccionEI = new javax.swing.JTextField();
        btnGuardarEI = new javax.swing.JButton();
        btnCancelarEU2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIdVecinoEI = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtNombreEI = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtApellidosEI = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtTelefonoEI = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtEmailEI = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VIU Comunidad");
        setResizable(false);

        panelCabecera.setBackground(new java.awt.Color(255, 255, 255));

        btnLiquidaciones.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnLiquidaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnLiquidaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pago.png"))); // NOI18N
        btnLiquidaciones.setText("Liquidaciones");
        btnLiquidaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnProveedores.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(51, 51, 51));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/proveedor.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnGastos.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnGastos.setForeground(new java.awt.Color(51, 51, 51));
        btnGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gastos.png"))); // NOI18N
        btnGastos.setText("Gastos");
        btnGastos.setToolTipText("");
        btnGastos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnServicios.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(51, 51, 51));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Servicios.png"))); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnInmuebles.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnInmuebles.setForeground(new java.awt.Color(51, 51, 51));
        btnInmuebles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edificios.png"))); // NOI18N
        btnInmuebles.setText("Inmuebles");
        btnInmuebles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInmuebles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInmueblesMouseClicked(evt);
            }
        });

        btnUsuarios.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usuarios.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });

        panelCabecera.setLayer(btnLiquidaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCabecera.setLayer(btnProveedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCabecera.setLayer(btnGastos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCabecera.setLayer(btnServicios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCabecera.setLayer(btnInmuebles, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCabecera.setLayer(btnUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLiquidaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLiquidaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        panelFooter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Tipo:");

        jLabel36.setForeground(new java.awt.Color(153, 153, 153));
        jLabel36.setText("Usuario:");

        jLabel37.setForeground(new java.awt.Color(153, 153, 153));
        jLabel37.setText("XXXXXXXXX");

        jLabel38.setForeground(new java.awt.Color(153, 153, 153));
        jLabel38.setText("Administrador");

        jLabel42.setForeground(new java.awt.Color(153, 153, 153));
        jLabel42.setText("XXXXXXXXX");

        panelFooter.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelFooter.setLayer(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelFooter.setLayer(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelFooter.setLayer(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelFooter.setLayer(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addContainerGap())
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel42))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icono2.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("72 Light", 1, 12)); // NOI18N
        jLabel34.setText("VIU Comunidad (Grupo3)");

        jLabel35.setFont(new java.awt.Font("72 Light", 0, 12)); // NOI18N
        jLabel35.setText("Gestión y Administración de Comunidades");

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelDatos.setPreferredSize(new java.awt.Dimension(1000, 600));

        gestionUsuariosFrame.setBackground(new java.awt.Color(255, 255, 255));
        gestionUsuariosFrame.setBorder(null);
        gestionUsuariosFrame.setForeground(new java.awt.Color(255, 255, 255));
        gestionUsuariosFrame.setTitle("Gestion Usuarios");
        gestionUsuariosFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        gestionUsuariosFrame.setVisible(false);

        btnAltaVecinoGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnAltaVecinoGU.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaVecinoGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alta_vecino.png"))); // NOI18N
        btnAltaVecinoGU.setText("Alta Vecino");
        btnAltaVecinoGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaVecinoGU.setOpaque(true);
        btnAltaVecinoGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaVecinoGUMouseClicked(evt);
            }
        });

        btnAltaAdminGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnAltaAdminGU.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaAdminGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gerente.png"))); // NOI18N
        btnAltaAdminGU.setText("Alta Administrador");
        btnAltaAdminGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaAdminGU.setOpaque(true);
        btnAltaAdminGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaAdminGUMouseClicked(evt);
            }
        });

        btnEditarUsuarioGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnEditarUsuarioGU.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarUsuarioGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/editar.png"))); // NOI18N
        btnEditarUsuarioGU.setText("Editar");
        btnEditarUsuarioGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnEditarUsuarioGU.setOpaque(true);
        btnEditarUsuarioGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioGUMouseClicked(evt);
            }
        });

        btnBorrarUsuarioGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnBorrarUsuarioGU.setForeground(new java.awt.Color(51, 51, 51));
        btnBorrarUsuarioGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/borrar.png"))); // NOI18N
        btnBorrarUsuarioGU.setText("Eliminar");
        btnBorrarUsuarioGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBorrarUsuarioGU.setOpaque(true);
        btnBorrarUsuarioGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarUsuarioGUMouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nombre");

        gUNombreText.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        gUNombreText.setForeground(new java.awt.Color(51, 51, 51));

        btnFiltrarUsuariosGU.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnFiltrarUsuariosGU.setForeground(new java.awt.Color(51, 51, 51));
        btnFiltrarUsuariosGU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar.png"))); // NOI18N
        btnFiltrarUsuariosGU.setText("Consultar");
        btnFiltrarUsuariosGU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnFiltrarUsuariosGU.setOpaque(true);
        btnFiltrarUsuariosGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarUsuariosGUMouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Apellidos", "Telefono", "Email", "userName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        btnBorrarUsuarioGU3.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnBorrarUsuarioGU3.setForeground(new java.awt.Color(51, 51, 51));
        btnBorrarUsuarioGU3.setText("Cancelar");
        btnBorrarUsuarioGU3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBorrarUsuarioGU3.setOpaque(true);
        btnBorrarUsuarioGU3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarUsuarioGU3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gestionUsuariosFrameLayout = new javax.swing.GroupLayout(gestionUsuariosFrame.getContentPane());
        gestionUsuariosFrame.getContentPane().setLayout(gestionUsuariosFrameLayout);
        gestionUsuariosFrameLayout.setHorizontalGroup(
            gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionUsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(gestionUsuariosFrameLayout.createSequentialGroup()
                        .addGroup(gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gestionUsuariosFrameLayout.createSequentialGroup()
                                .addComponent(btnAltaVecinoGU, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAltaAdminGU, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarUsuarioGU, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarUsuarioGU, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrarUsuarioGU3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gestionUsuariosFrameLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gUNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFiltrarUsuariosGU, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gestionUsuariosFrameLayout.setVerticalGroup(
            gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestionUsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAltaAdminGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAltaVecinoGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarUsuarioGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarUsuarioGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarUsuarioGU3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gestionUsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(gUNombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarUsuariosGU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        registroAdminFrame.setBackground(new java.awt.Color(255, 255, 255));
        registroAdminFrame.setBorder(null);
        registroAdminFrame.setForeground(new java.awt.Color(255, 255, 255));
        registroAdminFrame.setTitle("Registro Administrador");
        registroAdminFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        registroAdminFrame.setVisible(false);

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nombre");

        txtNombreRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtNombreRA.setForeground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Password");

        txtPasswordRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtPasswordRA.setText("password");
        txtPasswordRA.setToolTipText("");
        txtPasswordRA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordRAFocusGained(evt);
            }
        });

        btnAltaAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAltaAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaAdmin.setText("Aceptar");
        btnAltaAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaAdmin.setOpaque(true);
        btnAltaAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaAdminMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Apellidos");

        txtApellidosRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtApellidosRA.setForeground(new java.awt.Color(51, 51, 51));

        txtUserNameRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtUserNameRA.setForeground(new java.awt.Color(51, 51, 51));

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("User name");

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Telefono");

        txtTelefonoRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtTelefonoRA.setForeground(new java.awt.Color(51, 51, 51));

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Em@il");

        txtEmailRA.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        txtEmailRA.setForeground(new java.awt.Color(51, 51, 51));

        btnCancelarAltaAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarAltaAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarAltaAdmin.setText("Cancelar");
        btnCancelarAltaAdmin.setToolTipText("");
        btnCancelarAltaAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarAltaAdmin.setOpaque(true);
        btnCancelarAltaAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarAltaAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout registroAdminFrameLayout = new javax.swing.GroupLayout(registroAdminFrame.getContentPane());
        registroAdminFrame.getContentPane().setLayout(registroAdminFrameLayout);
        registroAdminFrameLayout.setHorizontalGroup(
            registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroAdminFrameLayout.createSequentialGroup()
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroAdminFrameLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroAdminFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailRA, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registroAdminFrameLayout.createSequentialGroup()
                        .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registroAdminFrameLayout.createSequentialGroup()
                                .addComponent(txtUserNameRA, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPasswordRA))
                            .addGroup(registroAdminFrameLayout.createSequentialGroup()
                                .addComponent(txtNombreRA, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidosRA, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefonoRA, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroAdminFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        registroAdminFrameLayout.setVerticalGroup(
            registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroAdminFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNombreRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtApellidosRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtTelefonoRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtEmailRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtUserNameRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtPasswordRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registroAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarAltaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        edicionVecinoFrame.setBackground(new java.awt.Color(255, 255, 255));
        edicionVecinoFrame.setBorder(null);
        edicionVecinoFrame.setForeground(new java.awt.Color(255, 255, 255));
        edicionVecinoFrame.setTitle("Editar / Detalle Vecino");
        edicionVecinoFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        edicionVecinoFrame.setVisible(false);

        jLabel29.setBackground(new java.awt.Color(51, 51, 51));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Id");

        txtIdEU.setEditable(false);
        txtIdEU.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtIdEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Nombre");

        txtNombreEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtNombreEU.setForeground(new java.awt.Color(51, 51, 51));

        txtApellidosEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtApellidosEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Apellidos");

        txtTelefonoEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtTelefonoEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Telefono");

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Em@il");

        txtEmailEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtEmailEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("User name");

        txtUserNameEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtUserNameEU.setForeground(new java.awt.Color(51, 51, 51));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Password");

        txtPasswordEU.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtPasswordEU.setText("password");
        txtPasswordEU.setToolTipText("");
        txtPasswordEU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordEUFocusGained(evt);
            }
        });

        btnGuardarEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardarEU.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarEU.setText("Guardar");
        btnGuardarEU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGuardarEU.setOpaque(true);
        btnGuardarEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarEUMouseClicked(evt);
            }
        });

        btnCancelarEU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarEU.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarEU.setText("Cancelar");
        btnCancelarEU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarEU.setOpaque(true);
        btnCancelarEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEUMouseClicked(evt);
            }
        });

        jTable3.setBackground(new java.awt.Color(242, 242, 242));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Inmuebles Asociados:");

        btnCancelarEU1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarEU1.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarEU1.setText("Detalle");
        btnCancelarEU1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarEU1.setOpaque(true);
        btnCancelarEU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEU1MouseClicked(evt);
            }
        });
        btnCancelarEU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEU1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edicionVecinoFrameLayout = new javax.swing.GroupLayout(edicionVecinoFrame.getContentPane());
        edicionVecinoFrame.getContentPane().setLayout(edicionVecinoFrameLayout);
        edicionVecinoFrameLayout.setHorizontalGroup(
            edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edicionVecinoFrameLayout.createSequentialGroup()
                        .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailEU, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                                        .addComponent(txtUserNameEU, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23))
                                    .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                                        .addComponent(txtNombreEU)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApellidosEU, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoEU)
                                    .addComponent(txtPasswordEU, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                    .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                        .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edicionVecinoFrameLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edicionVecinoFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelarEU1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        edicionVecinoFrameLayout.setVerticalGroup(
            edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edicionVecinoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(txtTelefonoEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserNameEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtPasswordEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(edicionVecinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEU1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        gestionInmueblesFrame.setBackground(new java.awt.Color(255, 255, 255));
        gestionInmueblesFrame.setBorder(null);
        gestionInmueblesFrame.setForeground(new java.awt.Color(255, 255, 255));
        gestionInmueblesFrame.setTitle("Gestion Inmuebles");
        gestionInmueblesFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        gestionInmueblesFrame.setVisible(false);

        btnAltaInmuebleGI.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnAltaInmuebleGI.setForeground(new java.awt.Color(51, 51, 51));
        btnAltaInmuebleGI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edificios.png"))); // NOI18N
        btnAltaInmuebleGI.setText("Alta Inmueble");
        btnAltaInmuebleGI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAltaInmuebleGI.setOpaque(true);
        btnAltaInmuebleGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaInmuebleGIMouseClicked(evt);
            }
        });

        btnEditarInmuebleGI.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnEditarInmuebleGI.setForeground(new java.awt.Color(51, 51, 51));
        btnEditarInmuebleGI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/editar.png"))); // NOI18N
        btnEditarInmuebleGI.setText("Editar");
        btnEditarInmuebleGI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnEditarInmuebleGI.setOpaque(true);
        btnEditarInmuebleGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarInmuebleGIMouseClicked(evt);
            }
        });

        btnBorrarInmuebleGI.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnBorrarInmuebleGI.setForeground(new java.awt.Color(51, 51, 51));
        btnBorrarInmuebleGI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/borrar.png"))); // NOI18N
        btnBorrarInmuebleGI.setText("Eliminar");
        btnBorrarInmuebleGI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBorrarInmuebleGI.setOpaque(true);
        btnBorrarInmuebleGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarInmuebleGIMouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Direccion");

        gIDireccionText.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        gIDireccionText.setForeground(new java.awt.Color(51, 51, 51));

        btnFiltrarInmueblesGI.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnFiltrarInmueblesGI.setForeground(new java.awt.Color(51, 51, 51));
        btnFiltrarInmueblesGI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar.png"))); // NOI18N
        btnFiltrarInmueblesGI.setText("Consultar");
        btnFiltrarInmueblesGI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnFiltrarInmueblesGI.setOpaque(true);
        btnFiltrarInmueblesGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarInmueblesGIMouseClicked(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Direccion", "Propietario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        btnCancelarGI.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        btnCancelarGI.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarGI.setText("Cancelar");
        btnCancelarGI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarGI.setOpaque(true);
        btnCancelarGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarGIMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gestionInmueblesFrameLayout = new javax.swing.GroupLayout(gestionInmueblesFrame.getContentPane());
        gestionInmueblesFrame.getContentPane().setLayout(gestionInmueblesFrameLayout);
        gestionInmueblesFrameLayout.setHorizontalGroup(
            gestionInmueblesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionInmueblesFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestionInmueblesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(gestionInmueblesFrameLayout.createSequentialGroup()
                        .addComponent(btnAltaInmuebleGI, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarInmuebleGI, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarInmuebleGI, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarGI, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(gestionInmueblesFrameLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gIDireccionText, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiltrarInmueblesGI, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gestionInmueblesFrameLayout.setVerticalGroup(
            gestionInmueblesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestionInmueblesFrameLayout.createSequentialGroup()
                .addGroup(gestionInmueblesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAltaInmuebleGI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(btnEditarInmuebleGI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarGI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarInmuebleGI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestionInmueblesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addGroup(gestionInmueblesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFiltrarInmueblesGI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gIDireccionText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        edicionInmuebleFrame.setBackground(new java.awt.Color(255, 255, 255));
        edicionInmuebleFrame.setBorder(null);
        edicionInmuebleFrame.setForeground(new java.awt.Color(255, 255, 255));
        edicionInmuebleFrame.setTitle("Editar / Detalle Inmueble");
        edicionInmuebleFrame.setPreferredSize(new java.awt.Dimension(986, 586));
        edicionInmuebleFrame.setVisible(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel30.setBackground(new java.awt.Color(51, 51, 51));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Id");

        txtIdEI.setEditable(false);
        txtIdEI.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEI.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtIdEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Dirección");

        txtDireccionEI.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtDireccionEI.setForeground(new java.awt.Color(51, 51, 51));

        btnGuardarEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardarEI.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarEI.setText("Guardar");
        btnGuardarEI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGuardarEI.setOpaque(true);
        btnGuardarEI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarEIMouseClicked(evt);
            }
        });

        btnCancelarEU2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarEU2.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarEU2.setText("Cancelar");
        btnCancelarEU2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarEU2.setOpaque(true);
        btnCancelarEU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEU2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtIdEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDireccionEI)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarEI, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnCancelarEU2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEU2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Vecino Asociado:");

        txtIdVecinoEI.setEditable(false);
        txtIdVecinoEI.setBackground(new java.awt.Color(255, 255, 255));
        txtIdVecinoEI.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtIdVecinoEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel31.setBackground(new java.awt.Color(51, 51, 51));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Id");

        txtNombreEI.setEditable(false);
        txtNombreEI.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEI.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtNombreEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel32.setBackground(new java.awt.Color(51, 51, 51));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Nombre");

        jLabel39.setBackground(new java.awt.Color(51, 51, 51));
        jLabel39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Apellidos");

        txtApellidosEI.setEditable(false);
        txtApellidosEI.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidosEI.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtApellidosEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel40.setBackground(new java.awt.Color(51, 51, 51));
        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Telefono");

        txtTelefonoEI.setEditable(false);
        txtTelefonoEI.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoEI.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtTelefonoEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel41.setBackground(new java.awt.Color(51, 51, 51));
        jLabel41.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("Em@il");

        txtEmailEI.setEditable(false);
        txtEmailEI.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailEI.setFont(new java.awt.Font("72 Light", 0, 14)); // NOI18N
        txtEmailEI.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtIdVecinoEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtNombreEI, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidosEI))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtTelefonoEI, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmailEI, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdVecinoEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellidosEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelefonoEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout edicionInmuebleFrameLayout = new javax.swing.GroupLayout(edicionInmuebleFrame.getContentPane());
        edicionInmuebleFrame.getContentPane().setLayout(edicionInmuebleFrameLayout);
        edicionInmuebleFrameLayout.setHorizontalGroup(
            edicionInmuebleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edicionInmuebleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(edicionInmuebleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        edicionInmuebleFrameLayout.setVerticalGroup(
            edicionInmuebleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edicionInmuebleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        panelDatos.setLayer(gestionUsuariosFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDatos.setLayer(registroAdminFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDatos.setLayer(edicionVecinoFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDatos.setLayer(gestionInmueblesFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDatos.setLayer(edicionInmuebleFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1018, Short.MAX_VALUE)
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gestionUsuariosFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(registroAdminFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edicionInmuebleFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(edicionVecinoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap()))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gestionInmueblesFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gestionUsuariosFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(registroAdminFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(edicionVecinoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(edicionInmuebleFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gestionInmueblesFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCabecera)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)))
                    .addComponent(panelFooter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFooter)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordRAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordRAFocusGained
        txtPasswordRA.setText("");
    }//GEN-LAST:event_txtPasswordRAFocusGained

    private void btnAltaAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaAdminMouseClicked
        uc.registrarAdmin();
        uc.cargarTablaUsuarios(gUNombreText.getText());
        registroAdminFrame.hide();
    }//GEN-LAST:event_btnAltaAdminMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        uc.cargarTablaUsuarios(gUNombreText.getText());
        if (gestionUsuariosFrame.isVisible() == false) {
            dimensionarFrameDatos(gestionUsuariosFrame);
        }
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void btnInmueblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInmueblesMouseClicked
        if (gestionInmueblesFrame.isVisible() == false) {
            dimensionarFrameDatos(gestionInmueblesFrame);
        }
        gestionInmueblesFrame.show();
    }//GEN-LAST:event_btnInmueblesMouseClicked

    private void txtPasswordEUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordEUFocusGained
        txtPasswordEU.setText("");
    }//GEN-LAST:event_txtPasswordEUFocusGained

    private void btnGuardarEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEUMouseClicked
        if(txtIdEU.getText().equals("")){
            uc.registrarVecino();
        }else{
            uc.updateUsuario();
        }
        edicionVecinoFrame.hide();;
    }//GEN-LAST:event_btnGuardarEUMouseClicked

    private void btnCancelarEUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEUMouseClicked
        edicionVecinoFrame.hide();
    }//GEN-LAST:event_btnCancelarEUMouseClicked

    private void btnCancelarAltaAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarAltaAdminMouseClicked
        registroAdminFrame.hide();
    }//GEN-LAST:event_btnCancelarAltaAdminMouseClicked

    private void btnBorrarUsuarioGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioGUMouseClicked
        uc.eliminarUsuario();
    }//GEN-LAST:event_btnBorrarUsuarioGUMouseClicked

    private void btnEditarUsuarioGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioGUMouseClicked
        if (jTable1.getSelectedRow() > 0) {
            if (edicionVecinoFrame.isVisible() == false) {
                dimensionarFrameDatos(edicionVecinoFrame);
            }
            uc.cargarFormUsuario();
            edicionVecinoFrame.show();
        }
    }//GEN-LAST:event_btnEditarUsuarioGUMouseClicked

    private void btnFiltrarUsuariosGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarUsuariosGUMouseClicked
        uc.cargarTablaUsuarios(gUNombreText.getText());
    }//GEN-LAST:event_btnFiltrarUsuariosGUMouseClicked

    private void btnAltaAdminGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaAdminGUMouseClicked
        if (registroAdminFrame.isVisible() == false) {
            dimensionarFrameDatos(registroAdminFrame);
        }
        registroAdminFrame.show();
    }//GEN-LAST:event_btnAltaAdminGUMouseClicked

    private void btnAltaVecinoGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaVecinoGUMouseClicked
        if (edicionVecinoFrame.isVisible() == false) {
            dimensionarFrameDatos(edicionVecinoFrame);
        }
        limpiarUserForm();
        edicionVecinoFrame.show();
    }//GEN-LAST:event_btnAltaVecinoGUMouseClicked

    private void btnCancelarEU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEU1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEU1MouseClicked

    private void btnCancelarEU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEU1ActionPerformed

    private void btnCancelarEU2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEU2MouseClicked
        edicionInmuebleFrame.hide();
    }//GEN-LAST:event_btnCancelarEU2MouseClicked

    private void btnAltaInmuebleGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaInmuebleGIMouseClicked
        if(edicionInmuebleFrame.isVisible()==false){
            dimensionarFrameDatos(edicionInmuebleFrame);
        }
        limpiarInmuebleForm();
        edicionInmuebleFrame.show();
    }//GEN-LAST:event_btnAltaInmuebleGIMouseClicked

    private void btnEditarInmuebleGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarInmuebleGIMouseClicked
        if (jTable2.getSelectedRow() > 0) {
            if (edicionInmuebleFrame.isVisible() == false) {
                dimensionarFrameDatos(edicionInmuebleFrame);
            }
            ic.cargarFormInmueble();
            edicionInmuebleFrame.show();
        }
    }//GEN-LAST:event_btnEditarInmuebleGIMouseClicked

    private void btnBorrarInmuebleGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarInmuebleGIMouseClicked
        ic.eliminarInmueble();
    }//GEN-LAST:event_btnBorrarInmuebleGIMouseClicked

    private void btnFiltrarInmueblesGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarInmueblesGIMouseClicked
        ic.cargarTablaInmuebles(gIDireccionText.getText());
    }//GEN-LAST:event_btnFiltrarInmueblesGIMouseClicked

    private void btnCancelarGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarGIMouseClicked
        gestionInmueblesFrame.hide();
    }//GEN-LAST:event_btnCancelarGIMouseClicked

    private void btnBorrarUsuarioGU3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioGU3MouseClicked
        gestionUsuariosFrame.hide();
    }//GEN-LAST:event_btnBorrarUsuarioGU3MouseClicked

    private void btnGuardarEIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEIMouseClicked
        ic.registrarInmueble();
    }//GEN-LAST:event_btnGuardarEIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameAdmin().setVisible(true);
            }
        });
    }

    private void dimensionarFrameDatos(JInternalFrame jIF) {
        jIF.setLocation((btnUsuarios.location().x),
                (btnUsuarios.location().y + btnUsuarios.getSize().height + 5));
        jIF.setSize(JFrame.WIDTH - 30, JFrame.HEIGHT - jLabel4.getSize().height - 30 - btnUsuarios.getSize().height);
        jIF.setVisible(true);
        jIF.show();

    }
    private void limpiarUserForm(){
        txtIdEU.setText("");
        txtNombreEU.setText("");
        txtApellidosEU.setText("");
        txtTelefonoEU.setText("");
        txtEmailEU.setText("");
        txtUserNameEU.setText("");
        txtPasswordEU.setText("");
    }
    
    private void limpiarInmuebleForm(){
        txtIdEI.setText("");
        txtDireccionEI.setText("");
        txtApellidosEI.setText("");
        txtTelefonoEI.setText("");
        txtEmailEI.setText("");
        txtNombreEI.setText("");
    }
    public void inicioMain() {
        edicionVecinoFrame.hide();
        gestionUsuariosFrame.hide();
        registroAdminFrame.hide();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaAdmin;
    private javax.swing.JButton btnAltaAdminGU;
    private javax.swing.JButton btnAltaInmuebleGI;
    private javax.swing.JButton btnAltaVecinoGU;
    private javax.swing.JButton btnBorrarInmuebleGI;
    private javax.swing.JButton btnBorrarUsuarioGU;
    private javax.swing.JButton btnBorrarUsuarioGU3;
    private javax.swing.JButton btnCancelarAltaAdmin;
    private javax.swing.JButton btnCancelarEU;
    private javax.swing.JButton btnCancelarEU1;
    private javax.swing.JButton btnCancelarEU2;
    private javax.swing.JButton btnCancelarGI;
    private javax.swing.JButton btnEditarUsuarioGU;
    private javax.swing.JButton btnFiltrarInmueblesGI;
    private javax.swing.JButton btnFiltrarUsuariosGU;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton btnGuardarEI;
    private javax.swing.JButton btnGuardarEU;
    private javax.swing.JButton btnInmuebles;
    private javax.swing.JButton btnLiquidaciones;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnUsuarios;
    public javax.swing.JInternalFrame edicionInmuebleFrame;
    public javax.swing.JInternalFrame edicionVecinoFrame;
    public javax.swing.JTextField gIDireccionText;
    public javax.swing.JTextField gUNombreText;
    private javax.swing.JInternalFrame gestionInmueblesFrame;
    private javax.swing.JInternalFrame gestionUsuariosFrame;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    public javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JDesktopPane panelCabecera;
    private javax.swing.JDesktopPane panelDatos;
    private javax.swing.JDesktopPane panelFooter;
    public javax.swing.JInternalFrame registroAdminFrame;
    public javax.swing.JTextField txtApellidosEI;
    public javax.swing.JTextField txtApellidosEU;
    public javax.swing.JTextField txtApellidosRA;
    public javax.swing.JTextField txtDireccionEI;
    public javax.swing.JTextField txtEmailEI;
    public javax.swing.JTextField txtEmailEU;
    public javax.swing.JTextField txtEmailRA;
    public javax.swing.JTextField txtIdEI;
    public javax.swing.JTextField txtIdEU;
    public javax.swing.JTextField txtIdVecinoEI;
    public javax.swing.JTextField txtNombreEI;
    public javax.swing.JTextField txtNombreEU;
    public javax.swing.JTextField txtNombreRA;
    public javax.swing.JPasswordField txtPasswordEU;
    public javax.swing.JPasswordField txtPasswordRA;
    public javax.swing.JTextField txtTelefonoEI;
    public javax.swing.JTextField txtTelefonoEU;
    public javax.swing.JTextField txtTelefonoRA;
    public javax.swing.JTextField txtUserNameEU;
    public javax.swing.JTextField txtUserNameRA;
    // End of variables declaration//GEN-END:variables
}
