/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.inmueble;

import controlador.Controlador;
import controlador.modelos.InmuebleControlador;
import controlador.modelos.UsuarioControlador;


/**
 *
 * @author fersi
 */
public class AsignacionInmuebleFrame extends javax.swing.JInternalFrame {

    Controlador ctrl;
    InmuebleControlador ic;
    UsuarioControlador uc;
    /**
     * Creates new form AsignacionInmuebleFrame
     */
    public AsignacionInmuebleFrame() {
        initComponents();
        ctrl = new Controlador();
        ic = new InmuebleControlador();
        uc = new UsuarioControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblVecinosAI = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblInmueblesAI = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSeleccionarInmueblesAI = new javax.swing.JButton();
        btnSeleccionarVecinoAI = new javax.swing.JButton();
        btnFiltrarInmuebleAI = new javax.swing.JButton();
        btnFiltrarUserAI = new javax.swing.JButton();
        txtFiltrarInmuebleAI = new javax.swing.JTextField();
        txtFiltrarNombreAI = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblSeleccionInmueblesAI = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLimpiarTablaAI = new javax.swing.JButton();
        javax.swing.JButton btnLimpiarVecinoAI = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lblVecinoIdAI = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lblVecinoNombreAI = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        lblVecinoApellidosAI = new javax.swing.JLabel();
        btnAsignarInmueblesAI = new javax.swing.JButton();
        btnCancelarAIF = new javax.swing.JButton();

        setVisible(false);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblVecinosAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblVecinosAI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellidos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblVecinosAI);

        tblInmueblesAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblInmueblesAI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dirección", "Propietario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tblInmueblesAI);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Inmuebles");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Vecinos:");

        btnSeleccionarInmueblesAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSeleccionarInmueblesAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/seleccionar.png"))); // NOI18N
        btnSeleccionarInmueblesAI.setText("Seleccionar");
        btnSeleccionarInmueblesAI.setMaximumSize(new java.awt.Dimension(119, 22));
        btnSeleccionarInmueblesAI.setMinimumSize(new java.awt.Dimension(119, 22));
        btnSeleccionarInmueblesAI.setPreferredSize(new java.awt.Dimension(119, 22));
        btnSeleccionarInmueblesAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarInmueblesAIMouseClicked(evt);
            }
        });

        btnSeleccionarVecinoAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSeleccionarVecinoAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/seleccionar.png"))); // NOI18N
        btnSeleccionarVecinoAI.setText("Seleccionar");
        btnSeleccionarVecinoAI.setMaximumSize(new java.awt.Dimension(119, 24));
        btnSeleccionarVecinoAI.setMinimumSize(new java.awt.Dimension(119, 24));
        btnSeleccionarVecinoAI.setPreferredSize(new java.awt.Dimension(119, 24));
        btnSeleccionarVecinoAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarVecinoAIMouseClicked(evt);
            }
        });

        btnFiltrarInmuebleAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFiltrarInmuebleAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        btnFiltrarInmuebleAI.setText("Filtrar");
        btnFiltrarInmuebleAI.setMaximumSize(new java.awt.Dimension(85, 22));
        btnFiltrarInmuebleAI.setMinimumSize(new java.awt.Dimension(85, 22));
        btnFiltrarInmuebleAI.setPreferredSize(new java.awt.Dimension(85, 22));
        btnFiltrarInmuebleAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarInmuebleAIMouseClicked(evt);
            }
        });

        btnFiltrarUserAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFiltrarUserAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lupa.png"))); // NOI18N
        btnFiltrarUserAI.setText("Filtrar");
        btnFiltrarUserAI.setMaximumSize(new java.awt.Dimension(85, 22));
        btnFiltrarUserAI.setMinimumSize(new java.awt.Dimension(85, 22));
        btnFiltrarUserAI.setPreferredSize(new java.awt.Dimension(85, 22));
        btnFiltrarUserAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarUserAIMouseClicked(evt);
            }
        });

        txtFiltrarInmuebleAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtFiltrarNombreAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnSeleccionarInmueblesAI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionarVecinoAI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrarInmuebleAI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrarInmuebleAI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFiltrarNombreAI, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrarUserAI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFiltrarNombreAI)
                        .addComponent(btnFiltrarUserAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFiltrarInmuebleAI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(btnFiltrarInmuebleAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarInmueblesAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarVecinoAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblSeleccionInmueblesAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblSeleccionInmueblesAI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblSeleccionInmueblesAI);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Inmuebles seleccionados:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Vecino Seleccionado:");

        btnLimpiarTablaAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpiarTablaAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/escoba.png"))); // NOI18N
        btnLimpiarTablaAI.setText("Limpiar");
        btnLimpiarTablaAI.setMaximumSize(new java.awt.Dimension(96, 22));
        btnLimpiarTablaAI.setMinimumSize(new java.awt.Dimension(96, 22));
        btnLimpiarTablaAI.setPreferredSize(new java.awt.Dimension(96, 22));
        btnLimpiarTablaAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarTablaAIMouseClicked(evt);
            }
        });

        btnLimpiarVecinoAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpiarVecinoAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/escoba.png"))); // NOI18N
        btnLimpiarVecinoAI.setText("Limpiar");
        btnLimpiarVecinoAI.setMaximumSize(new java.awt.Dimension(96, 22));
        btnLimpiarVecinoAI.setMinimumSize(new java.awt.Dimension(96, 22));
        btnLimpiarVecinoAI.setPreferredSize(new java.awt.Dimension(96, 22));
        btnLimpiarVecinoAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarVecinoAIMouseClicked(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblVecinoIdAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblVecinoIdAI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblVecinoIdAI.setMaximumSize(new java.awt.Dimension(64, 20));
        lblVecinoIdAI.setMinimumSize(new java.awt.Dimension(64, 20));
        lblVecinoIdAI.setPreferredSize(new java.awt.Dimension(64, 20));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("ID");

        jLabel50.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel50.setText("Nombre:");

        lblVecinoNombreAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblVecinoNombreAI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblVecinoNombreAI.setPreferredSize(new java.awt.Dimension(64, 20));

        jLabel52.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel52.setText("Apellidos:");

        lblVecinoApellidosAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblVecinoApellidosAI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblVecinoApellidosAI.setMaximumSize(new java.awt.Dimension(64, 20));
        lblVecinoApellidosAI.setMinimumSize(new java.awt.Dimension(64, 20));
        lblVecinoApellidosAI.setPreferredSize(new java.awt.Dimension(64, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVecinoApellidosAI, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVecinoIdAI, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVecinoNombreAI, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(lblVecinoIdAI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVecinoNombreAI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(lblVecinoApellidosAI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnAsignarInmueblesAI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAsignarInmueblesAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/asignar.png"))); // NOI18N
        btnAsignarInmueblesAI.setText("Asignar");
        btnAsignarInmueblesAI.setMaximumSize(new java.awt.Dimension(96, 22));
        btnAsignarInmueblesAI.setMinimumSize(new java.awt.Dimension(96, 22));
        btnAsignarInmueblesAI.setName(""); // NOI18N
        btnAsignarInmueblesAI.setPreferredSize(new java.awt.Dimension(96, 22));
        btnAsignarInmueblesAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarInmueblesAIMouseClicked(evt);
            }
        });

        btnCancelarAIF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarAIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar.png"))); // NOI18N
        btnCancelarAIF.setText("Cancelar");
        btnCancelarAIF.setMaximumSize(new java.awt.Dimension(104, 22));
        btnCancelarAIF.setMinimumSize(new java.awt.Dimension(104, 22));
        btnCancelarAIF.setName(""); // NOI18N
        btnCancelarAIF.setPreferredSize(new java.awt.Dimension(104, 22));
        btnCancelarAIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarAIFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(337, 337, 337))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnLimpiarTablaAI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarVecinoAI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAsignarInmueblesAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(btnCancelarAIF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarVecinoAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarTablaAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarInmueblesAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarAIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarInmueblesAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarInmueblesAIMouseClicked
        ic.cargarTablaInmueblesSelected(
            tblInmueblesAI,
            tblSeleccionInmueblesAI,
            btnFiltrarInmuebleAI,
            btnLimpiarTablaAI,
            btnSeleccionarInmueblesAI,
            txtFiltrarInmuebleAI);
    }//GEN-LAST:event_btnSeleccionarInmueblesAIMouseClicked

    private void btnSeleccionarVecinoAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarVecinoAIMouseClicked
        uc.cargarVecinosSelected(tblVecinosAI, lblVecinoIdAI, lblVecinoNombreAI, lblVecinoApellidosAI);
    }//GEN-LAST:event_btnSeleccionarVecinoAIMouseClicked

    private void btnFiltrarInmuebleAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarInmuebleAIMouseClicked
        ic.cargarTablaInmuebles(txtFiltrarInmuebleAI.getText(), tblInmueblesAI);
    }//GEN-LAST:event_btnFiltrarInmuebleAIMouseClicked

    private void btnFiltrarUserAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarUserAIMouseClicked
        ic.cargarTablaVecinosAsignacion(txtFiltrarNombreAI.getText(), tblVecinosAI);
    }//GEN-LAST:event_btnFiltrarUserAIMouseClicked

    private void btnLimpiarTablaAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarTablaAIMouseClicked
        ctrl.limpiarTabla(tblSeleccionInmueblesAI);
    }//GEN-LAST:event_btnLimpiarTablaAIMouseClicked

    private void btnLimpiarVecinoAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarVecinoAIMouseClicked
        limpiarDatosUsuario();
    }//GEN-LAST:event_btnLimpiarVecinoAIMouseClicked

    private void btnAsignarInmueblesAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarInmueblesAIMouseClicked
        if (ic.comprobarAsignacion(tblSeleccionInmueblesAI, lblVecinoIdAI) == true) {
            ic.AsignarInmueble(tblSeleccionInmueblesAI, lblVecinoIdAI);
            limpiarDatosUsuario();
            ctrl.limpiarTabla(tblSeleccionInmueblesAI);
            ic.cargarTablaInmuebles("", tblInmueblesAI);
        }
    }//GEN-LAST:event_btnAsignarInmueblesAIMouseClicked

    private void btnCancelarAIFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarAIFMouseClicked
        GestionInmueblesFrame gif = new GestionInmueblesFrame();
        ic.cargarTablaInmuebles("", gif.tblInmueblesGIF);
        ctrl.ocultarFrame(this, ctrl.mfamvc.panelDatos );
        ctrl.mostrarFrame(gif, ctrl.mfamvc.panelDatos);
    }//GEN-LAST:event_btnCancelarAIFMouseClicked

    private void limpiarDatosUsuario() {
        lblVecinoIdAI.setText("");
        lblVecinoNombreAI.setText("");
        lblVecinoApellidosAI.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarInmueblesAI;
    private javax.swing.JButton btnCancelarAIF;
    public javax.swing.JButton btnFiltrarInmuebleAI;
    public javax.swing.JButton btnFiltrarUserAI;
    public javax.swing.JButton btnLimpiarTablaAI;
    public javax.swing.JButton btnSeleccionarInmueblesAI;
    public javax.swing.JButton btnSeleccionarVecinoAI;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel lblVecinoApellidosAI;
    public javax.swing.JLabel lblVecinoIdAI;
    public javax.swing.JLabel lblVecinoNombreAI;
    public javax.swing.JTable tblInmueblesAI;
    public javax.swing.JTable tblSeleccionInmueblesAI;
    public javax.swing.JTable tblVecinosAI;
    public javax.swing.JTextField txtFiltrarInmuebleAI;
    public javax.swing.JTextField txtFiltrarNombreAI;
    // End of variables declaration//GEN-END:variables
}
