/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.inmueble;

import controlador.Controlador;
import controlador.modelos.InmuebleControlador;
import controlador.modelos.LiquidacionControlador;
import controlador.modelos.ServicioControlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Inmueble;
import modelo.Liquidacion;
import modelo.LiquidacionDetalleGasto;
import modelo.LiquidacionDetalleServicio;
import modelo.Servicio;
import modelo.ServicioCuenta;
import modelo.usuario.Vecino;

/**
 *
 * @author fersi
 */
public class EdicionInmuebleFrame extends javax.swing.JInternalFrame {

    Controlador ctrl;
    InmuebleControlador ic;
    LiquidacionControlador lc;
    ServicioControlador sc;
    /**
     * Creates new form EdicionInmuebleFrame
     */
    public EdicionInmuebleFrame() {
        initComponents();
        ctrl = new Controlador();
        ic = new InmuebleControlador();
        sc = new ServicioControlador();
        lc = new LiquidacionControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        txtIdEI = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtDireccionEI = new javax.swing.JTextField();
        btnAsignarEI = new javax.swing.JButton();
        btnCancelarEI = new javax.swing.JButton();
        btnGuardarEI = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtIdVecinoEI = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtNombreEI = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtApellidosEI = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txtTelefonoEI = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtEmailEI = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblServiciosEI = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLiquidacionDetalleInmueble = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        tblLiquidacionInmuebleEI = new javax.swing.JTable();
        btnAsignarEI1 = new javax.swing.JButton();
        lblTotalEI = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel43.setBackground(new java.awt.Color(51, 51, 51));
        jLabel43.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setText("Id");

        txtIdEI.setEditable(false);
        txtIdEI.setBackground(new java.awt.Color(255, 255, 255));
        txtIdEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdEI.setForeground(new java.awt.Color(51, 51, 51));
        txtIdEI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdEIKeyTyped(evt);
            }
        });

        jLabel44.setBackground(new java.awt.Color(51, 51, 51));
        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setText("Dirección");

        txtDireccionEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDireccionEI.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccionEI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionEIKeyTyped(evt);
            }
        });

        btnAsignarEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAsignarEI.setForeground(new java.awt.Color(51, 51, 51));
        btnAsignarEI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/asignar.png"))); // NOI18N
        btnAsignarEI.setText("Asignar");
        btnAsignarEI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAsignarEI.setOpaque(true);
        btnAsignarEI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarEIMouseClicked(evt);
            }
        });

        btnCancelarEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarEI.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelarEI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar.png"))); // NOI18N
        btnCancelarEI.setText("Cancelar");
        btnCancelarEI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCancelarEI.setOpaque(true);
        btnCancelarEI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarEIMouseClicked(evt);
            }
        });

        btnGuardarEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardarEI.setForeground(new java.awt.Color(51, 51, 51));
        btnGuardarEI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salvar.png"))); // NOI18N
        btnGuardarEI.setText("Guardar");
        btnGuardarEI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGuardarEI.setOpaque(true);
        btnGuardarEI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarEIMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtIdEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDireccionEI)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarEI, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsignarEI, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnCancelarEI, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarEI)
                    .addComponent(btnCancelarEI)
                    .addComponent(btnGuardarEI))
                .addGap(14, 14, 14))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Vecino Asociado:");

        txtIdVecinoEI.setEditable(false);
        txtIdVecinoEI.setBackground(new java.awt.Color(255, 255, 255));
        txtIdVecinoEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdVecinoEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel45.setBackground(new java.awt.Color(51, 51, 51));
        jLabel45.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setText("Id");

        txtNombreEI.setEditable(false);
        txtNombreEI.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel46.setBackground(new java.awt.Color(51, 51, 51));
        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 51, 51));
        jLabel46.setText("Nombre");

        jLabel47.setBackground(new java.awt.Color(51, 51, 51));
        jLabel47.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("Apellidos");

        txtApellidosEI.setEditable(false);
        txtApellidosEI.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidosEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtApellidosEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel48.setBackground(new java.awt.Color(51, 51, 51));
        jLabel48.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("Telefono");

        txtTelefonoEI.setEditable(false);
        txtTelefonoEI.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelefonoEI.setForeground(new java.awt.Color(51, 51, 51));

        jLabel49.setBackground(new java.awt.Color(51, 51, 51));
        jLabel49.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Em@il");

        txtEmailEI.setEditable(false);
        txtEmailEI.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmailEI.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtIdVecinoEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtNombreEI, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidosEI))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtTelefonoEI, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailEI)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdVecinoEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellidosEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelefonoEI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tblServiciosEI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tarifa", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblServiciosEI);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane2.addTab("Servicios", jPanel1);

        tblLiquidacionDetalleInmueble.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblLiquidacionDetalleInmueble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "Descripcion", "Cuota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblLiquidacionDetalleInmueble);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Liquidaciones:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Detalle Liquidación:");

        tblLiquidacionInmuebleEI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblLiquidacionInmuebleEI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha Inicio", "Fecha Fin", "Cuota"
            }
        ));
        jScrollPane26.setViewportView(tblLiquidacionInmuebleEI);

        btnAsignarEI1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAsignarEI1.setForeground(new java.awt.Color(51, 51, 51));
        btnAsignarEI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/asignar.png"))); // NOI18N
        btnAsignarEI1.setText("Consultar");
        btnAsignarEI1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnAsignarEI1.setOpaque(true);
        btnAsignarEI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarEI1MouseClicked(evt);
            }
        });

        lblTotalEI.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalEI.setForeground(new java.awt.Color(255, 153, 153));
        lblTotalEI.setText("#####");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(btnAsignarEI1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalEI)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalEI)
                    .addComponent(btnAsignarEI1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Liquidaciones", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void txtIdEIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEIKeyTyped
        String texto = txtIdEI.getText();
        char caracter = evt.getKeyChar();
        if (ctrl.filtrarCaracteres(texto,caracter,"n")){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdEIKeyTyped
    /**
     * 
     * @param evt 
     */
    private void txtDireccionEIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionEIKeyTyped
        String texto = txtDireccionEI.getText();
        char caracter = evt.getKeyChar();
        if (ctrl.filtrarCaracteres(texto,caracter,"ln")){
            evt.consume();
        }
    }//GEN-LAST:event_txtDireccionEIKeyTyped
    /**
     * 
     * @param evt 
     */
    private void btnAsignarEIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarEIMouseClicked
        AsignacionInmuebleFrame aif = new AsignacionInmuebleFrame();
        ctrl.ocultarFrameAdmin(this);
        ctrl.mostrarFrameAdmin(aif);
        aif.cargarTablaInmueblesFromEdit(ic.obtenerInmueble(Integer.parseInt(txtIdEI.getText())));
        aif.cargarTablaVecinosAsignacion("");
    }//GEN-LAST:event_btnAsignarEIMouseClicked

    /**
     * 
     * @param evt 
     */
    private void btnCancelarEIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEIMouseClicked
        ctrl.ocultarFrameAdmin(this);
    }//GEN-LAST:event_btnCancelarEIMouseClicked

    /**
     * 
     * @param evt 
     */
    private void btnGuardarEIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEIMouseClicked
        GestionInmueblesFrame gif = new GestionInmueblesFrame();
        if (txtIdEI.getText().equals("")) {
            String direccion = txtDireccionEI.getText();
            ic.registrarInmueble(direccion);
        } else {
            int id = Integer.parseInt(txtIdEI.getText());
            String direccion = txtDireccionEI.getText();
            String idVecino = txtIdVecinoEI.getText();
            ic.updateInmueble(id, direccion, idVecino);
        }
        gif.cargarTablaInmuebles("");
        ctrl.ocultarFrameAdmin(this);
        ctrl.mostrarFrameAdmin(gif);
    }//GEN-LAST:event_btnGuardarEIMouseClicked

    /**
     * 
     * @param evt 
     */
    private void btnAsignarEI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarEI1MouseClicked
        if(tblLiquidacionInmuebleEI.getSelectedRowCount()>0){
            int row = tblLiquidacionInmuebleEI.getSelectedRow();
            int idLiquidacion = (int)tblLiquidacionInmuebleEI.getValueAt(row, 0);
            cargarTablaLiquidacionDetalleInmueble(Integer.parseInt(txtIdEI.getText()), idLiquidacion, lblTotalEI, tblLiquidacionDetalleInmueble);
        }
    }//GEN-LAST:event_btnAsignarEI1MouseClicked

    /**
     * 
     */
    public void limpiarInmuebleForm() {
        txtIdEI.setText("");
        txtDireccionEI.setText("");
        txtApellidosEI.setText("");
        txtTelefonoEI.setText("");
        txtEmailEI.setText("");
        txtNombreEI.setText("");
    }
    /**
     * 
     * @param id 
     */
    public void cargarFormInmueble(int id) {
        Inmueble i = ic.obtenerInmueble(id);
        txtIdEI.setText(Integer.toString(i.getId()));
        txtDireccionEI.setText(i.getDireccion());
        Vecino v = i.getVecino();
        if (v != null) {
            txtIdVecinoEI.setText(Integer.toString(v.getId()));
            txtNombreEI.setText(v.getNombre());
            txtApellidosEI.setText(v.getApellidos());
            txtTelefonoEI.setText(v.getTelefono());
            txtEmailEI.setText(v.getEmail());
        } else {
            txtIdVecinoEI.setText("");
            txtNombreEI.setText("");
            txtApellidosEI.setText("");
            txtTelefonoEI.setText("");
            txtEmailEI.setText("");
        }

    }
    /**
     * 
     * @param idInmueble 
     */
    public void cargarTablaServiciosInmueble(int idInmueble) {
        DefaultTableModel model = (DefaultTableModel) tblServiciosEI.getModel();
        model.setNumRows(0);
        List <ServicioCuenta> listaServicioCuenta = ic.listarServiciosInmueble(idInmueble);
        String tipoServicio;
        for(ServicioCuenta scta : listaServicioCuenta){
          Servicio s = sc.obtenerServicio(scta.getServicio().getId());
            if(s.isOpcional()==true){
                tipoServicio = "Opcional";
            }else{
                tipoServicio = "Obligatorio";
            }
            model.addRow(new Object[]{s.getId(), s.getNombre(), s.getTarifa(), tipoServicio});
        }
    }
    /**
     * 
     * @param idInmueble 
     */
    public void cargarTablaLiquidacionesInmueble(int idInmueble) {
        String tipo;
        List <ServicioCuenta> listaServicioCuenta = ic.listarServiciosInmueble(idInmueble);
        List<Liquidacion> lista = new ArrayList();
        DefaultTableModel model = (DefaultTableModel) tblLiquidacionInmuebleEI.getModel();
        model.setNumRows(0);
        for(ServicioCuenta scta : listaServicioCuenta){
            lista = lc.buscarLiquidacionInmueble(scta.getId());
            for (int i = 0; i < lista.size(); i++) {
            model.addRow(new Object[]{lista.get(i).getId(), lista.get(i).getFechaInicio(), lista.get(i).getFechaFin()});
            }
        }
    }
    /**
     * 
     * @param idInmueble
     * @param idLiquidacion
     * @param lblTotalEI
     * @param tabla 
     */
    public void cargarTablaLiquidacionDetalleInmueble(int idInmueble, int idLiquidacion, JLabel lblTotalEI, JTable tabla) {
        String tipo;
        Liquidacion l = lc.obtenerLiquidacion(idLiquidacion);
        Double cuotaFinal = 0.0;
        List<LiquidacionDetalleServicio> listaServicios = lc.serviciosLiquidadosInmueble(idInmueble, idLiquidacion);
        List<LiquidacionDetalleGasto> listaGastos = lc.gastosLiquidadosInmueble(idInmueble, idLiquidacion);
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setNumRows(0);
        for (int i = 0; i < listaServicios.size(); i++) {
            model.addRow(new Object[]{"SERVICIO", listaServicios.get(i).getSc().getServicio().getNombre(), listaServicios.get(i).getCuota()});
            Double cuota = listaServicios.get(i).getCuota();
            cuotaFinal += cuota;
        }
        for (int i = 0; i < listaGastos.size(); i++) {
            model.addRow(new Object[]{"GASTO", listaGastos.get(i).getGastoLiquidacion(), listaGastos.get(i).getCuota()});
            Double cuota = listaGastos.get(i).getCuota();
            cuotaFinal += cuota;
        }
        lblTotalEI.setText(String.format("%,.2f", cuotaFinal) + "€");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarEI;
    private javax.swing.JButton btnAsignarEI1;
    private javax.swing.JButton btnCancelarEI;
    private javax.swing.JButton btnGuardarEI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblTotalEI;
    public javax.swing.JTable tblLiquidacionDetalleInmueble;
    public javax.swing.JTable tblLiquidacionInmuebleEI;
    public javax.swing.JTable tblServiciosEI;
    public javax.swing.JTextField txtApellidosEI;
    public javax.swing.JTextField txtDireccionEI;
    public javax.swing.JTextField txtEmailEI;
    public javax.swing.JTextField txtIdEI;
    public javax.swing.JTextField txtIdVecinoEI;
    public javax.swing.JTextField txtNombreEI;
    public javax.swing.JTextField txtTelefonoEI;
    // End of variables declaration//GEN-END:variables
}
